name: CI/CD Pipeline for ShareSphere

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers the workflow on versioned tags like v1.2.3

jobs:
  build:
    name: Build and Validate across Python Versions
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
      fail-fast: false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Cache Poetry Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
            ~/.cache/pip
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: '1.4.2'

      - name: Install Dependencies
        run: poetry install --no-interaction --no-ansi

      - name: Basic Import Check
        run: |
          poetry run python -c "import sharesphere"

      - name: Validate Poetry Configuration
        run: poetry check

      - name: Build Package
        run: poetry build --no-interaction --no-ansi

      - name: Upload Built Package as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: sharesphere-package
          path: dist/*.whl

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v2.1
        with:
          python_version: "3.11"
          pypi_token: ${{ secrets.PYPI_TOKEN }}

